apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-2nbr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-2nbr@sha256:00407af8c77cf8f7513d964511bee25a72a7e12504ec74a84149ea5c9ef46d2b
        name: my-nodejs
        resources: {}
status: {}
